### ISSUE TITLE
Ubuntu install instructions Broken

### ISSUE THREAD

**Issue by jimrthy** [StanfordSNR/guardian-agent#32]
When I tried to download the latest release using command-line tools, I wound up with an extra redirect link with a bunch of X-Amz parameters added as part of the URL.

When I tried to curl/wget that, I got an error about missing one or more of those parameters.

When I used the basic query (to curl for the latest release page, followed by grepping/cutting) to get the "real" URL and then opened that using links, I was able to download the tarball without any problems.

I know this is basically abandonware, but it seems worth mentioning in case anyone else runs across the problem in the future.

**Comment by keithw** [comment]
Hmm, I can't replicate this -- it works for me. Maybe AWS had a transient error.

guardian-agent doesn't seem to be abandonware; you are getting a response in 48 hours to your bug report, and the software still works. If there's a bug and it goes unfixed, then you can call it abandonware!

```
$ curl -L https://api.github.com/repos/StanfordSNR/guardian-agent/releases/latest | grep browser_download_url | grep 'linux' | cut -d'"' -f 4 | xargs curl -Ls | tar zt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5373  100  5373    0     0  26467      0 --:--:-- --:--:-- --:--:-- 26338
sga_linux_amd64/
sga_linux_amd64/sga-env.sh
sga_linux_amd64/sga-guard
sga_linux_amd64/sga-guard-bin
sga_linux_amd64/sga-ssh
sga_linux_amd64/sga-stub
```

**Comment by jimrthy** [comment]
I'm really sorry about calling this "abandonware." I thought it was quite clear from the README that this was an academic project, and that it's done. I must have read incorrectly, and I cannot apologize enough.
